name: juice
description: An interpreter for timeseries operations
version: 0.0.4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dama:
    git: https://github.com/thumbert/dama.git
  date:
    git: https://github.com/thumbert/date.git
  elec:
    git: https://github.com/thumbert/elec.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  petitparser: ^6.0.1

dev_dependencies:
  build_runner: '>=1.6.2 <3.0.0'
  build_web_compilers: '>=2.12.0 <4.0.0'
  csv: ^5.0.1
  date:
    git: https://github.com/thumbert/date.git
  lints: ^3.0.0
  test: ^1.24.9
  timezone: ^0.9.2
