name: juice
description: An interpreter for timeseries operations
version: 0.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  date:
    git: https://github.com/thumbert/date.git
  elec:
    git: https://github.com/thumbert/elec.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.7.0

dev_dependencies:
  csv: ^5.0.1
  lints: ^2.0.0
  test: ^1.16.0
