name: juice
description: An interpreter for timeseries operations
version: 0.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  date:
    git: https://github.com/thumbert/date.git
  elec:
    git: https://github.com/thumbert/elec.git
  js: ^0.6.7
  petitparser: ^5.1.0
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.8.0

dev_dependencies:
  build_runner: '>=1.6.2 <3.0.0'
  build_web_compilers: '>=2.12.0 <4.0.0'
  csv: ^5.0.1
  lints: ^2.0.0
  test: ^1.16.0
